#Internet Analytics and Prediction Service for Cloud Applications (IAPS) {#slug-one}

Global Internet Characteristic Feedback Loop for Cloud Applications
 
#### Keywords {-}
 internet analytics, internet traffic statistics, internet performance, predictive network modelling for cloud apps

## Background
The Internet has democratized a lot of industries and has had a transformational economic impact across the globe. But the internet infrastructure itself is not democratized, all internet users are not equal. The cost, network bandwidth and performance of the internet vary substantially across the globe. This poses significant challenges for businesses that rely on the global internet infrastructure for their business. Consider an application such as Uber or YouTube, these applications can potentially exhibit different experiences in San Francisco compared to a tier-2 or tier-3 city in other parts of the world, depending on the internet and mobile characteristics of the region. 

This research aims to apply data science techniques to analyze the cost, bandwidth and a performance characteristics of internet connectivity across major global regions and develop a cloud service to provide analytical insights and prediction capabilities for geo specific networks. This will help globally connected businesses with better insights in understanding the impact and implications to their cloud applications.

## Proposal

Businesses depend on the internet for their daily operations. Applications hosted in a cloud need to interact with their users across the world. Currently the applications rely on best-effort guarantees of the internet. The users are based across the world and will have varied internet characterizes depending on their geographical location and hence varied end user experiences.

The proposal aims to collect, analyze and predict the internet characteristic data of the client’s geographical environment and aims to provide a service to be used by applications hosted in the cloud so they can build geo appropriate user experiences which eventually will lead to improved business outcomes. 

IAPS can be categorized in four disting components

1. Internet Characteristic Data Collection Engine

This component of IAPS is reponsible for collecting internet data from various sources (TBD) and categorizing into into seperate geo locations.

2. Analytics Engine

The analytics engine aims to provide analysis of the metrics such as throughput, latency, bandwidth, outages per geo-locations.

3. Perdiction Engine

The predication engine aims to build a predicive model based on observed behaviour

4. Realtime Service for reporting current geo-conditions 

A realtime IAPS service will provide reporting capabilities of network metrics for buisnesses to use


## Conclusion
Understanding and adapting to Network Connectivity characteristics worldwide will differentiate and help cloud applications. This project aims to help businesses answer sample questions such as – why is my mobile gaming app experience different in 20 major cities of the world and how can I improve it, when can my automobile design business transfer large set of databases (Petabytes) from USA to a multiple global team across the world. This list can go on and is applicable across the spectrum specifically to businesses which do not possess deep technological knowledge and resources.

References:
[@cisco-internet-stats]



